# Generated by Django 3.1.7 on 2021-03-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamBuilderApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid1',
            new_name='User_ID',
        ),
    ]
