# Generated by Django 3.1.2 on 2020-11-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamBuilderApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
